Update git version for CentOS 7 from 1.8 to 2.27
This patch updates git version from 1.8 to 2.27 in CentOS 7 Dockerfile.
The CentOS 7 PackPack image may be used in a containerized GitHub
Actions job, which requires atleast git 2.18 to check out submodules
recursively. Without this change, one will get the following error when
calling the `actions/checkout` action:

    Error: Input 'submodules' not supported when falling back to
    download using the GitHub REST API. To create a local Git repository
    instead, add Git 2.18 or higher to the PATH.